---
title: Scrabble two letter words
output:
 html_document:
      theme: flatly
      highlight: textmate
---

```{r markdown, echo = FALSE, warning = FALSE}
library(knitr)
library(devtools)
opts_chunk$set(echo = TRUE, eval = TRUE, cache = FALSE, comment = "")
```

```{r setup, message = FALSE, warning = FALSE}
library(stringr)
library(dplyr)
library(purrr)
library(magrittr)
library(glue)
library(here)
library(listviewer)
```

```{r}
extract_words <- function(letter, words = words_all) {
  
  list(letter = letter,
       all = str_subset(words, letter),
       first = str_subset(words, glue("^", {letter})),
       second = str_subset(words, glue({letter}, "$")))
}
```

```{r}
words_all <- c("aa", "ab", "ad", "ae", "ag", "ah", "ai", "al", "am", "an", "ar", "as", "at", "aw", "ax", "ay", "ba", "be", "bi", "bo", "by", "ch", "da", "de", "di", "do", "ea", "ed", "ee", "ef", "eh", "el", "em", "en", "er", "es", "et", "ex", "fa", "fe", "fy", "gi", "go", "gu", "ha", "he", "hi", "hm", "ho", "id", "if", "in", "io", "is", "it", "ja", "jo", "ka", "ki", "ko", "ky", "la", "li", "lo", "ma", "me", "mi", "mm", "mo", "mu", "my", "na", "ne", "no", "nu", "ny", "ob", "od", "oe", "of", "oh", "oi", "om", "on", "oo", "op", "or", "os", "ou", "ow", "ox", "oy", "pa", "pe", "pi", "po", "qi", "re", "sh", "si", "so", "st", "ta", "te", "ti", "to", "ug", "uh", "um", "un", "up", "ur", "us", "ut", "we", "wo", "xi", "xu", "ya", "ye", "yo", "yu", "za", "zo")
```

```{r}

two_letter_list <- map(letters, extract_words)
str(two_letter_list, list.len = 4, max.level = 2)
listviewer::jsonedit(two_letter_list, mode = "view")
```

```{r}
# remember { to prevent two_letter_list being passed into tibble
two_letter <- two_letter_list %>% {
  tibble(
     first = map(., "second"),
     letter = map_chr(., "letter"),
     second = map(.,"first")
  )} %T>% 
  saveRDS(here("two_letter.rds")) %>% 
  glimpse()
```


